### Configuration file for hdf_to_dataloader.py script ###
### loading radar map data from hdf format and exporting it as torch DataLoader ###

rootdir: C:\Users\marti\kinit\radar-dataset-preprocess\2016-01-11 # directory of input hdf files  - at this point no subfolders are supported - TODO
outdir: C:\Users\marti\kinit\radar-dataset-preprocess\output # directory where to save output h5 files
# radar pictures related parameters
image_capture_interval: 300 # interval between two radar image captures in seconds
grid_shape: [1, 340, 340] # TODO map this to numbers in code
grid_limits: [[2000, 2000], [-170000.0, 170000.0], [-170000.0, 170000.0]] # TODO map this to numbers in code
a: 200.0 # parameter a of the Z/R relationship Standard value according to Marshall-Palmer is a=200
b: 1.6 # parameter b of the Z/R relationship Standard value according to Marshall-Palmer is b=1.6
rainy_pxl_threshold: 0.05 # threshold for determining whether the pixel of radar picture is rainy or not (mm of rain per capture interval)
rainy_img_threshold: 0.2 # threshold for determining whether the radar picture is rainy or not (percentage of rainy pixels in image)
input_length: 6 # how many images we want to base our prediction on
target_length: 6 # how many images we want to forecast into future

